- name: create directory
  file:
    path: ~/code/suckless
    state: directory

- name: install fonts
  pacman:
    name: "{{ item }}"
  become: yes
  loop:
    - ttf-hack
    - ttf-font-awesome

- name: install and config
  include_tasks: suckless-software.yml
  loop: "{{ suckless_software }}"
