- name: create directory
  file:
    path: ~/code/suckless
    state: directory

- name: install hack font
  pacman:
    name: ttf-hack
  become: yes

- name: install and config
  include_tasks: suckless-software.yml
  loop: "{{ suckless_software }}"
