- name: clone repo
  git:
    repo: git@github.com:jeremingo/{{ item.name }}.git
    dest: ~/code/suckless/{{ item.name }}

- name: configure upstream url
  git_config:
    name: remote.upstream.url
    repo: ~/code/suckless/{{ item.name }}
    scope: local
    value: "{{ item.upstream_url }}"

- name: configure upstream fetch
  git_config:
    name: remote.upstream.fetch
    repo: ~/code/suckless/{{ item.name }}
    scope: local
    value: +refs/heads/*:refs/remotes/upstream/*
