- name: clone repo
  git:
    repo: git@github.com:jeremingo/{{ item.name }}.git
    dest: ~/code/suckless/{{ item.name }}
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in the destination' in repo_clone.msg

- name: configure upstream url
  git_config:
    name: remote.upstream.url
    repo: ~/code/suckless/{{ item.name }}
    scope: local
    value: "{{ item.upstream_url }}"

- name: configure upstream fetch
  git_config:
    name: remote.upstream.fetch
    repo: ~/code/suckless/{{ item.name }}
    scope: local
    value: +refs/heads/*:refs/remotes/upstream/*
