- name: install qmk
  pacman:
    name: qmk
  become: yes

- name: clone qmk firmware
  git:
    repo: https://github.com/qmk/qmk_firmware.git
    dest: ~/code/qmk/firmware

- name: clone qmk userspace
  git:
    repo: git@github.com:jeremingo/qmk_userspace.git
    dest: ~/code/qmk/userspace

- name: set qmk home in config
  command:
    cmd: 'qmk config {{ item.key }}={{ item.value }}'
  register: qmk_config_output
  changed_when: item.value + ' -> ' + item.value not in qmk_config_output.stdout
  loop: '{{ qmk_config | dict2items }}'

- name: link userspace keyboards into firmware
  file:
    src: '{{ ansible_env.HOME }}/code/qmk/userspace/keyboards/jeremingo'
    dest: '{{ ansible_env.HOME }}/code/qmk/firmware/keyboards/jeremingo'
    state: link
